services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "45679:45679" # zpages extension

  go_service_a:
    build:
      context: ./Service_A
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - otel-collector
    environment:
      - WEATHER_API_KEY=b71c9fa1897546c2832221527240810
      - OTEL_SERVICE_NAME=service_A
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317

  go_service_b:
    build:
      context: ./Service_B
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - otel-collector
    environment:
      - WEATHER_API_KEY=b71c9fa1897546c2832221527240810
      - OTEL_SERVICE_NAME=service_B
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317